/**
 * GameOverPanel
 * 
 * This panel is shown after all shots are taken. It displays the 
 * player's final score, lets them enter their name, and save the score
 * to the high scores list. It also includes a Play Again button and an Exit button.
 * 
 */
package penaltiesgame;

import java.io.*;
import javax.swing.*;

/**
 *
 * @author Siddhi 
 */
public class GameOverPanel extends javax.swing.JPanel {

    PenaltiesGame mainFrame; // Reference to the main frame to allow panel switching
    
    int finalScore =0; //initializes final score
    /*Method to display final score from the game panel*/
    public void setFinalScore(int score) {
        lblFinalScore.setText("Final Score: " + score + " / 5"); //displays the score in the text area box
        this.finalScore = score; //stores the final score from the gaem panel
    }
    
    /*Method to re-enable the save button to save the score for multiple games*/
    public void resetSaveButton() {
        btnSaveScore.setEnabled(true); //enables the save button
        txtPlayerName.setText(""); //clears the name input field
    }
    

    
    /** 
     * Creates new form GameOverPanel
     */
    public GameOverPanel() {
        initComponents();
    }

    GameOverPanel(PenaltiesGame frame) {
       initComponents();
       this.mainFrame = frame; //connects the panel to the main frame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        lblFinalScore = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        btnPlayAgain = new javax.swing.JButton();
        lblEnterName = new javax.swing.JLabel();
        txtPlayerName = new javax.swing.JTextField();
        btnSaveScore = new javax.swing.JButton();
        btnHighScores = new javax.swing.JButton();
        CelebrationImage = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        setLayout(null);

        Title.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        Title.setForeground(new java.awt.Color(246, 39, 39));
        Title.setText("Game Over!");
        add(Title);
        Title.setBounds(300, 20, 180, 37);

        lblFinalScore.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        lblFinalScore.setText("Score:");
        add(lblFinalScore);
        lblFinalScore.setBounds(320, 70, 170, 50);

        btnHome.setBackground(new java.awt.Color(254, 211, 167));
        btnHome.setText("Back to Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        add(btnHome);
        btnHome.setBounds(40, 500, 170, 41);

        btnPlayAgain.setBackground(new java.awt.Color(127, 176, 244));
        btnPlayAgain.setText("Play Again!");
        btnPlayAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayAgainActionPerformed(evt);
            }
        });
        add(btnPlayAgain);
        btnPlayAgain.setBounds(510, 500, 135, 41);

        lblEnterName.setText("Enter Your Name to Save Your Score:");
        add(lblEnterName);
        lblEnterName.setBounds(140, 140, 210, 33);
        add(txtPlayerName);
        txtPlayerName.setBounds(370, 140, 170, 39);

        btnSaveScore.setText("Save Score");
        btnSaveScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveScoreActionPerformed(evt);
            }
        });
        add(btnSaveScore);
        btnSaveScore.setBounds(580, 140, 150, 41);

        btnHighScores.setBackground(new java.awt.Color(240, 196, 243));
        btnHighScores.setText("View Highscores");
        btnHighScores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHighScoresActionPerformed(evt);
            }
        });
        add(btnHighScores);
        btnHighScores.setBounds(260, 500, 200, 41);

        CelebrationImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penaltiesgame/images/Soccer celebration.gif"))); // NOI18N
        add(CelebrationImage);
        CelebrationImage.setBounds(190, 210, 610, 260);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        add(btnExit);
        btnExit.setBounds(690, 500, 80, 41);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        /*Changes to home panel*/
        mainFrame.setContentPane(mainFrame.HomePanel);
        mainFrame.revalidate();
        mainFrame.repaint();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnPlayAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayAgainActionPerformed
        resetSaveButton(); //re-enables the save button
        /*Changes to the game panel with the game reset and ready to play*/
        mainFrame.GamePanel.resetGame(); //resets game
        mainFrame.setContentPane(mainFrame.GamePanel); //changes to game panel
        mainFrame.revalidate();
        mainFrame.repaint();
    }//GEN-LAST:event_btnPlayAgainActionPerformed

    private void btnHighScoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHighScoresActionPerformed
        /*Changes to the high scores panel*/
        mainFrame.HighScoresPanel.reloadScores();
        mainFrame.setContentPane(mainFrame.HighScoresPanel);
        mainFrame.revalidate();
        mainFrame.repaint(); 
    }//GEN-LAST:event_btnHighScoresActionPerformed

    private void btnSaveScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveScoreActionPerformed
        String playerName = txtPlayerName.getText(); //gets the player's name input
        
        if (playerName.isEmpty()) { //if no name is entered
            JOptionPane.showMessageDialog(this, "Please enter your name before saving."); //displays error message
        return;
        }

        try {
            FileWriter writer = new FileWriter("highscores.txt", true); // appends each line
            writer.write(playerName + " - " + finalScore + "\n"); //writes name and score
            writer.close(); //closes writer

            JOptionPane.showMessageDialog(this, "Score saved successfully!"); //displays a successful save
            txtPlayerName.setText(""); // clears field after saving
            btnSaveScore.setEnabled(false); // disables button to prevent duplicate saves

        } 
        catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving score: " + e.getMessage()); //error message if unable to write in text file
        }
    }//GEN-LAST:event_btnSaveScoreActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0); //exits the application
    }//GEN-LAST:event_btnExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CelebrationImage;
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHighScores;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnPlayAgain;
    private javax.swing.JButton btnSaveScore;
    private javax.swing.JLabel lblEnterName;
    private javax.swing.JLabel lblFinalScore;
    private javax.swing.JTextField txtPlayerName;
    // End of variables declaration//GEN-END:variables
}
