/**
 * HighScoresPanel
 * 
 * This panel displays the list of saved high scores. It supports 
 * searching for a player’s scores and sorting by highest score and name.
 * Data is read and written from a text file named "highscores.txt".
 * 
 */
package penaltiesgame;

import java.io.*;
import java.util.*;
import javax.swing.*; 

/**
 *
 * @author Siddhi 
 */
public class HighScoresPanel extends javax.swing.JPanel {

    PenaltiesGame mainFrame; // Reference to the main frame to allow panel switching
    
    /**
     * Loads and displays all scores from the highscores.txt file into the JTextArea.
     * Each line of the file is expected in the format "Name - Score".
     */
    public void loadHighScores() {
    File file = new File("highscores.txt"); //access the file
    try (BufferedReader br = new BufferedReader(new FileReader(file))) {
        String line;
            while ((line = br.readLine()) != null) { //reads each line
                txtScoresList.append(line + "\n"); // Displays in JTextArea
            }
        } 
    catch (IOException e) {
        e.printStackTrace();
        }
    }
    
    /**
     * Clears the JTextArea and reloads the scores.
     * Useful after saving new scores or refreshing after sorting/searching.
     */
    public void reloadScores() {
        txtScoresList.setText(""); // Clear previous content
        loadHighScores(); // recalls the method that reads from the file
        revalidate();
        repaint();
    }
    
    /**
     * Creates new form HighScoresPanel
     */
    public HighScoresPanel() {
        initComponents();
    }

    HighScoresPanel(PenaltiesGame frame) {
       initComponents();
       this.mainFrame = frame; //connects the panel to the main frame
       loadHighScores(); //calls method to show all the saved scores
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        ScoresDisplay = new javax.swing.JScrollPane();
        txtScoresList = new javax.swing.JTextArea();
        btnAllScores = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblSearchInstructions = new javax.swing.JLabel();
        txtPlayerName = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnSort = new javax.swing.JButton();
        KickGIF = new javax.swing.JLabel();
        TrophyImage = new javax.swing.JLabel();

        setLayout(null);

        Title.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        Title.setForeground(new java.awt.Color(153, 153, 255));
        Title.setText("High Scores!");
        add(Title);
        Title.setBounds(280, 20, 210, 37);

        btnHome.setBackground(new java.awt.Color(254, 211, 167));
        btnHome.setText("Back to Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        add(btnHome);
        btnHome.setBounds(560, 510, 170, 30);

        txtScoresList.setColumns(20);
        txtScoresList.setRows(5);
        ScoresDisplay.setViewportView(txtScoresList);

        add(ScoresDisplay);
        ScoresDisplay.setBounds(240, 150, 310, 340);

        btnAllScores.setText("Show All Scores");
        btnAllScores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllScoresActionPerformed(evt);
            }
        });
        add(btnAllScores);
        btnAllScores.setBounds(40, 100, 150, 30);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        add(btnExit);
        btnExit.setBounds(100, 510, 80, 30);

        lblSearchInstructions.setText("Enter a name to Search scores:");
        add(lblSearchInstructions);
        lblSearchInstructions.setBounds(240, 90, 240, 33);
        add(txtPlayerName);
        txtPlayerName.setBounds(420, 90, 190, 39);

        btnSearch.setBackground(new java.awt.Color(204, 255, 204));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch);
        btnSearch.setBounds(640, 90, 120, 41);

        btnSort.setText("Sort");
        btnSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortActionPerformed(evt);
            }
        });
        add(btnSort);
        btnSort.setBounds(330, 510, 90, 30);

        KickGIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penaltiesgame/images/Ball kick.gif"))); // NOI18N
        add(KickGIF);
        KickGIF.setBounds(20, 160, 210, 320);

        TrophyImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penaltiesgame/images/trophy.png"))); // NOI18N
        add(TrophyImage);
        TrophyImage.setBounds(610, 180, 140, 280);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        /*Changes to the home panel*/
        mainFrame.setContentPane(mainFrame.HomePanel);
        mainFrame.revalidate();
        mainFrame.repaint();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String name = txtPlayerName.getText().trim().toLowerCase(); //gets the player name input and trims it and makes it lower case to make sure there are no errors in input
        
        if (name.isEmpty()) { //if not name is entered
            JOptionPane.showMessageDialog(this, "Enter a player name to search."); //displays an error message
            return;
        }
        
        try {
            BufferedReader reader = new BufferedReader(new FileReader("highscores.txt")); //accesses the file
            StringBuilder results = new StringBuilder(); //creates a string for the result
            String line;

            while ((line = reader.readLine()) != null) { //reads file by line
                if (line.toLowerCase().startsWith(name + " -")) { //looks for first part of the line (name -)
                    results.append(line).append("\n"); //creates a new line if the player has more than one saved score to display them all
            }
        }
        
        reader.close(); //closes file

            if (results.length() == 0) { //if no reults found
                txtScoresList.setText("No scores found for: " + name); //displays appropriate message
            } 
            else { //if results found
                txtScoresList.setText(results.toString()); //displays name and scores
            }
        } 
        catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error reading highscores: " + e.getMessage()); //error message if file is not read properly
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAllScoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllScoresActionPerformed
        reloadScores(); //calls the method to clear the text area box and display all the scores again
    }//GEN-LAST:event_btnAllScoresActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0); //exits the application
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortActionPerformed
        try {
            BufferedReader reader = new BufferedReader(new FileReader("highscores.txt")); //accesses the text file
            List<String> lines = new ArrayList<>(); //creates an ArrayList for each line in the text file
            String line;

            /*Loads all the lines into the list*/
            while ((line = reader.readLine()) != null) {
                lines.add(line);
        }

        reader.close(); //closes the file
        
       // Sorts by score descending, then name ascending
       Collections.sort(lines, new Comparator<String>() {
        public int compare(String a, String b) {
                /*Splits up name and score*/
                String[] partsA = a.split(" - ");
                String[] partsB = b.split(" - ");
                
                int scoreA = Integer.parseInt(partsA[1]);
                int scoreB = Integer.parseInt(partsB[1]);

            /*First sorts by score descending*/
                int scoreCompare = Integer.compare(scoreB, scoreA); // descending
                if (scoreCompare != 0) return scoreCompare;

            /*Then sorts by name ascending*/
            return partsA[0].compareToIgnoreCase(partsB[0]);
         }
        });
        
        /* Displays sorted result*/
        StringBuilder sortedText = new StringBuilder();
        for (int i = 0; i < lines.size(); i++) {
            sortedText.append(lines.get(i)).append("\n"); //line by line
        }

        txtScoresList.setText(sortedText.toString()); //displays in text area box

        } 
        catch (IOException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error sorting highscores: " + e.getMessage()); //error message if file is not read properly
        }
    }//GEN-LAST:event_btnSortActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel KickGIF;
    private javax.swing.JScrollPane ScoresDisplay;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel TrophyImage;
    private javax.swing.JButton btnAllScores;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSort;
    private javax.swing.JLabel lblSearchInstructions;
    private javax.swing.JTextField txtPlayerName;
    private javax.swing.JTextArea txtScoresList;
    // End of variables declaration//GEN-END:variables
}
