/**
 * HomePanel
 * 
 * This panel displays the home screen of the game and allows 
 * the user to navigate to the game, view high scores, or exit.
 * 
 */
package penaltiesgame;


import javax.swing.*;
import java.awt.event.*;
import java.awt.*;

/**
 *
 * @author Siddhi 
 */
public class HomePanel extends javax.swing.JPanel {

    PenaltiesGame mainFrame; // Reference to the main frame to allow panel switching
    /**
     * Creates new form HomePanel
     */
    public HomePanel() {
        initComponents(); 
    }

    HomePanel(PenaltiesGame frame) {
        initComponents();
        this.mainFrame = frame; //connects the panel to the main frame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked") 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPlay = new javax.swing.JButton();
        btnViewHighScores = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        Instructions = new javax.swing.JLabel();
        Image = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        setBackground(new java.awt.Color(6, 163, 49));
        setLayout(null);

        btnPlay.setBackground(new java.awt.Color(127, 175, 247));
        btnPlay.setText("Play!");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        add(btnPlay);
        btnPlay.setBounds(300, 470, 89, 41);

        btnViewHighScores.setBackground(new java.awt.Color(240, 196, 243));
        btnViewHighScores.setText("View High Scores");
        btnViewHighScores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHighScoresActionPerformed(evt);
            }
        });
        add(btnViewHighScores);
        btnViewHighScores.setBounds(470, 470, 237, 41);

        Title.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        Title.setText("Soccer Penalties Game");
        add(Title);
        Title.setBounds(220, 30, 344, 37);

        Instructions.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Instructions.setForeground(new java.awt.Color(253, 253, 253));
        Instructions.setText("Welcome to Penalties Game! Click on Play to Start showing off your soccer skills.");
        add(Instructions);
        Instructions.setBounds(90, 100, 953, 33);

        Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penaltiesgame/images/homescreen.jpg"))); // NOI18N
        add(Image);
        Image.setBounds(100, 170, 570, 250);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        add(btnExit);
        btnExit.setBounds(90, 470, 100, 41);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        /*Changes to game panel*/
        mainFrame.GamePanel.resetGame();
        mainFrame.setContentPane(mainFrame.GamePanel);
        mainFrame.revalidate();
        mainFrame.repaint();
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnViewHighScoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHighScoresActionPerformed
        /*Changes to high scores panel*/
        mainFrame.setContentPane(mainFrame.HighScoresPanel); 
        mainFrame.revalidate();
        mainFrame.repaint(); 
    }//GEN-LAST:event_btnViewHighScoresActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0); //exits the application
    }//GEN-LAST:event_btnExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Image;
    private javax.swing.JLabel Instructions;
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnViewHighScores;
    // End of variables declaration//GEN-END:variables
}
