/*
Programmer: Siddhi Patel
Date: June 10, 2025
Program Name: Soccer Penalties Game
Program Description: This program simulates a real-life soccer penalties game.
* This is the main program file which is used to switch between different game panels.
* This frame connects all the panels into one program.
* The home panel is set as the main panel that is first displayed when the program is run.
* This frame sets the defualt size and operations.
 */
package penaltiesgame;

import javax.swing.*;
import java.awt.event.*;
import java.awt.*;

/**
 *
 * @author Siddhi
 */ 
public class PenaltiesGame extends javax.swing.JFrame {

    /*Creates and connects game panels*/
    HomePanel HomePanel = new HomePanel(this); //creates home panel
    GamePanel GamePanel = new GamePanel(this); //creates game panel where game is played
    GameOverPanel GameOverPanel = new GameOverPanel(this); //creates game over panel
    HighScoresPanel HighScoresPanel = new HighScoresPanel(this); //creates high scores panel
    
    /**
     * Creates new form PenaltiesGame
     */
    public PenaltiesGame() {
        initComponents();
        setTitle("Soccer Penalties Game"); //sets title
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); //sets defualt close operation
        setSize(795, 600); //sets the size of the frame
        setLocationRelativeTo(null); //centers the frame on the computer screen
        setContentPane(HomePanel); // Start with Home Screen
        setVisible(true); //makes the frame and panels visible
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenaltiesGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenaltiesGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenaltiesGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenaltiesGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenaltiesGame().setVisible(true);
            } 
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
